name: Python application

on: [workflow_dispatch]

permissions:
  contents: read

env:
    REMOTE_REPO_URL: ${{ github.repository }},
    SNYK_TOKEN: ${{ vars.SNYK_TOKEN }},
    GH_TOKEN: ${{ github.token }},
    POETRY_VIRTUALENVS_CREATE: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install Poetry
      run: |
        pip install -U pip
        pip install poetry
        poetry install
          
    - name: Install dependencies
      run: poetry install --no-interaction --no-root
    - name: Find license issues and run check
      run: python ci_scripts_library/snyk_scm_license_check/cli.py snyk-license-check
